steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/b0noI/notebooks-ci-showcase']
- name: 'google/cloud-sdk:237.0.0'
  args: ['-c', './run_test.sh']
  dir: 'notebooks-ci-showcase'
  entrypoint: '/bin/bash'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['gsutil', 'cp', 'notebook.ipynb', 'gs://dl-platform-temp/notebook-ci-showcase/results/${BUILD_ID}/demo.ipynb']
  dir: 'notebooks-ci-showcase'
  entrypoint: '/bin/bash'
