steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/b0noI/notebooks-ci-showcase']
- name: 'google/cloud-sdk:237.0.0'
  args: ['-c', './run_test.sh']
  dir: 'notebooks-ci-showcase'
  entrypoint: '/bin/bash'
artifacts:
  objects:
    location: 'gs://dl-platform-temp/notebook-ci-showcase/results'
    paths: [ 'notebooks-ci-showcase/notebook.ipynb' ]