steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/b0noI/notebooks-ci-showcase']
- name: 'google/cloud-sdk:237.0.0'
  args: ['-c', './run_notebook_instance.sh -t']
  dir: 'notebooks-ci-showcase'
  entrypoint: '/bin/bash'
  secretEnv: ['API_KEY'] 
- name: 'google/cloud-sdk:237.0.0'
  args: ['-c', 'tar -zcvf live.tar.gz demo.ipynb notebook_executor.sh run_notebook_instance.sh']
  dir: 'notebooks-ci-showcase'
  entrypoint: '/bin/bash'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'live.tar.gz', 'gs://dl-platform-temp/notebook-ci-showcase/live.tar.gz']
  dir: 'notebooks-ci-showcase'
- name: 'google/cloud-sdk:237.0.0'
  args: ['-c', 'apt update && apt install -y zip && zip deploy.zip *']
  dir: 'notebooks-ci-showcase/deploy'
  entrypoint: '/bin/bash'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'deploy.zip', 'gs://dl-platform-temp/notebook-ci-showcase/deploy.zip']
  dir: 'notebooks-ci-showcase/deploy'
# For the next step, the cloud build service account must be granted the Cloud Functions Developer permission (not default).
- name: 'google/cloud-sdk:237.0.0'
  args: ['gcloud', 'functions', 'deploy', 'demo-notebook-function', '--region=us-central1', '--source=gs://dl-platform-temp/notebook-ci-showcase/deploy.zip']
secrets:
- kmsKeyName: projects/deeplearning-platform/locations/global/keyRings/api_key/cryptoKeys/google_maps_api
  secretEnv:
    API_KEY: CiQAqOZsWlDTXTRk/yjMO1BmEwto8Kboq90JG9zOuhizXsVO6fQSUQD7A7YryCuYQ+t6h9IL9Of6M+qCg/SezgvB/efTAGHhfzOYqa9mNMlECMo5hgnzpNjq6pPCauASAy8+VB+H4SLOfT9drLlpQTgxW3zTpAxtTQ==
